services:
  - type: web
    name: ai-app-compiler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY2
        sync: false
      - key: GEMINI_API_KEY3
        sync: false
      - key: GEMINI_API_KEY4
        sync: false
      - key: GEMINI_API_KEY5
        sync: false
      - key: GEMINI_API_KEY6
        sync: false
      - key: GEMINI_API_KEY7
        sync: false
      - key: GEMINI_API_KEY8
        sync: false
      - key: GEMINI_API_KEY9
        sync: false
      - key: GEMINI_API_KEY10
        sync: false
      